import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const SignSpan = (
    <span className="text-white" style={{ cursor: "pointer" }}>
      {user.isSignedIn ? "Sign out" : "Sign in"}
    </span>
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {user.isSignedIn ? (
          <SignOutButton>{SignSpan}</SignOutButton>
        ) : (
          <SignInButton>{SignSpan}</SignInButton>
        )}
      </main>
    </>
  );
};

export default Home;
